### ISSUE TITLE
US 02.05.03 - As an organizer I want to be able to draw a replacement applicant from the pooling system when a previously selected applicant cancels or rejects the invitation

### ISSUE THREAD

**Issue by hfmohammed** [CMPUT301F24zenith/zenith-events#18]
As an organizer I want to be able to draw a replacement applicant from the pooling system when a previously selected applicant cancels or rejects the invitation

**Comment by sobanshoaib** [comment]
Risk-level: High
Story Points: 1
This should be released by the half-way checkpoint.
