### ISSUE TITLE
US 02.02.03 - An organizer wants to enable or disable the geolocation requirement for my event.

### ISSUE THREAD

**Issue by akhafagy47** [CMPUT301F24zenith/zenith-events#47]
An organizer wants to enable or disable the geolocation requirement for my event.

**Comment by sobanshoaib** [comment]
Risk-level: High
Story Points: 5
This should be released by the half-way checkpoint.

**Comment by sobanshoaib** [comment]
No it does not need to be released by half-way checkpoint.
